name: Clone Repository on Remote Server

on:
  push:
    branches:
      - main

jobs:
  clone_repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH keys
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    - name: Clone repository
      run: ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa && git@github.com:rajan-addweb/github-demo.git'
